### ISSUE TITLE
Extended Menu Options

### ISSUE THREAD

**Issue by bmasephol** [deniapps/ckeditor5-build-classic-dna#12]
I stumbled across your project while trying to figure out how to keep bootstraps styles on the tables in the CKEditor content I'm creating.  

I managed to piece together how to use your project with my .Net Core project after sorting my way through npm and gulp in Visual Studio.

The question I have is prior to using your project I had used the CKEditors web site to put together all of the menu options I wanted to include in the classic editor but after updating to this version those are gone (as expected).  Is it possible to add those options back in while using your version of the editor?

**Comment by deniapps** [comment]
What's the "Menu Options" look like? Does it come with CKEditor 5 Classic Build (the official one)? Here is the way to customize the toolbar when using my build.
https://deniapps.com/blog/customize-ckeditor5-toolbar

**Comment by bmasephol** [comment]
I believe so, I used their website to "customize" my own build of CKEditor 5 and at the end you just download the .js file and reference it and you get your setup as you designed it.

![image](https://user-images.githubusercontent.com/12200343/160951093-d80358b1-bd0f-4a87-985a-62d11c2f5f10.png)

Maybe its possible to put it together by hand if the CKEditor you expanded on has "everything" in it.

**Comment by deniapps** [comment]
The menu options show when the screen is too small to hold all menus. So it shows automatically,  like below:
<img width="632" alt="image" src="https://user-images.githubusercontent.com/66892370/160953003-6e9e5430-a909-4283-a74d-8df7df11d935.png">

Do you have any particular menus wanted to add? Also, the toolbar on your screenshot looks like CKEditor4 not 5.

**Comment by bmasephol** [comment]
It's 5, but I believe during the online builder process you can customize things a little bit.

![image](https://user-images.githubusercontent.com/12200343/160955380-d2221ac2-8a0b-49da-b601-09d9bb31c06d.png)

![image](https://user-images.githubusercontent.com/12200343/160955617-7f5a0c8c-f627-40e6-a400-e70ba36e1f98.png)

I was just looking to add some more options around managing image placement/size.  I was just starting to do that when I stumbled across your project which fixed up my table display issues.  I could do some research and try to figure out specific ones.  I'd have to do some digging to figure out what the "names" of them are like you have examples for.

**Comment by bmasephol** [comment]
As a follow up, it seems like this is for sure one of the plugins I'm interested in.

https://ckeditor.com/docs/ckeditor5/latest/features/images/images-resizing.html#installation

Can I use that with your build?

**Comment by deniapps** [comment]
I just updated the package: https://www.npmjs.com/package/ckeditor5-build-classic-dna (v1.3.2) integrated with the latest ckeditor5 (v.33.0.0) and added the image resizing plugin.
I added the Image Resizing toolbar. Please check it out on the demo page: https://deniapps.com/playground/ckeditor

Note that you have to add "ImageResize" to the toolbar, and you can see how I did that at https://github.com/deniapps/nextfeathers/blob/master/next/components/Common/CKEditorDemo.js

Also, if you would like to add extra plugins, I think you can import them in your own code, and then add them to the "extraPlugins" array. Something like:

```
import ImageResizeEditing from '@ckeditor/ckeditor5-image/src/imageresize/imageresizeediting';
import ImageResizeHandles from '@ckeditor/ckeditor5-image/src/imageresize/imageresizehandles';

 <CKEditor
        editor={ClassicEditor}
        data={this.props.value}
        config={{
          table: {
            customClass: ["ui", "table", "celled"],
          },
          extraPlugins: [ImageResizeEditing, ImageResizeHandles],
...
```
Good luck!

**Comment by bmasephol** [comment]
Really appreciate the update and examples.  I updated to the latest package and was able to get things working.  Over the next few nights I'll see if I can try to pull in an additional plugin to see if I can get it to work.

I'm using pretty vanilla javascript/jquery in my asp.net core project, so the react and other examples I'm finding take me a bit to translate.

**Comment by bmasephol** [comment]
Had some time tonight to play around with trying to add an additional plugin.  I've determined that another I need is the CKFinder plugin as I was using that in my previous version to handle image uploads to save to the database.

Best I can tell the only way I can do this and keep your customizations is to do a fork of your repo and make the changes myself to include that plug and get that to build/publish.  That sound correct?

**Comment by deniapps** [comment]
I believe there is a way to integrate CKFinder (including other plugins) into your code (either React or Vanilla) without a rebuild. For example:
```
<script src="./node_modules/ckeditor5-build-classic-dna/build/ckeditor.js"></script>
<script src="https://ckeditor.com/apps/ckfinder/3.5.0/ckfinder.js"></script>

<script>
  ClassicEditor.create(document.querySelector("#editor"), 
     { plugins: [ CKFinder, ... ]} ) // I think you can add plugins here
    .then((editor) => {
      window.editor = editor;
    })
    .catch((error) => {
      console.error("There was a problem initializing the editor.", error);
    });
</script>
```
I think CKFinder is not free, so I did not add it to my build. And yes, you are free to fork my repo, add plugins and create your own build, and then use it in your project.

Hope this helps.
Adam

**Comment by bmasephol** [comment]
I went back and reviewed the .zip that I downloaded when I used the online builder and it was the CKFinderUploadAdapter plugin, not CKFinder.  I'll give a few things a try.  Appreciate your willingness to help.

**Comment by bmasephol** [comment]
Just wanted to let you know that I was able to get things working.  I ended up forking your repo and finding my way through adding in my own version of the ckeditor as a base and then adding on top of it some of your customizations, although I couldn't get some parts to work due to some NPM/WebPack errors about a secret file... I ended up just dropping a few things and was able to get the feature that I most wanted working, then ability to specify the table classes to make bootstrap styles work.  

Thanks again for you help!

**Comment by deniapps** [comment]
Glad you figured it out. Yeah, the Unsplash integrated into my plugin requires API keys, which are saved in a private file. So you cannot use it. When I get a chance, I will see if I can make it work better. 
Thank you for the updates. I am going to close the issue. If you have other questions, feel free to open a new one.
